const jd = [{
	"label": "安徽",
	"value": "14",
	"childrens": [{
		"label": "铜陵市",
		"value": "1114",
		"childrens": [{
			"label": "郊区",
			"value": "53480",
			"childrens": []
		}, {
			"label": "义安区",
			"value": "53481",
			"childrens": []
		}, {
			"label": "铜官区",
			"value": "53482",
			"childrens": []
		}, {
			"label": "枞阳县",
			"value": "53483",
			"childrens": []
		}]
	}, {
		"label": "合肥市",
		"value": "1116",
		"childrens": [{
			"label": "肥东县",
			"value": "1119",
			"childrens": []
		}, {
			"label": "庐江县",
			"value": "1190",
			"childrens": []
		}, {
			"label": "包河区",
			"value": "3431",
			"childrens": []
		}, {
			"label": "蜀山区",
			"value": "3432",
			"childrens": []
		}, {
			"label": "瑶海区",
			"value": "3433",
			"childrens": []
		}, {
			"label": "庐阳区",
			"value": "3434",
			"childrens": []
		}, {
			"label": "经济技术开发区",
			"value": "4173",
			"childrens": []
		}, {
			"label": "高新技术开发区",
			"value": "4192",
			"childrens": []
		}, {
			"label": "北城新区",
			"value": "6117",
			"childrens": []
		}, {
			"label": "滨湖新区",
			"value": "6118",
			"childrens": []
		}, {
			"label": "政务文化新区",
			"value": "6119",
			"childrens": []
		}, {
			"label": "新站综合开发试验区",
			"value": "6120",
			"childrens": []
		}, {
			"label": "肥西县",
			"value": "53484",
			"childrens": []
		}, {
			"label": "巢湖市",
			"value": "53485",
			"childrens": []
		}, {
			"label": "长丰县",
			"value": "53486",
			"childrens": []
		}]
	}, {
		"label": "淮南市",
		"value": "1121",
		"childrens": [{
			"label": "凤台县",
			"value": "1122",
			"childrens": [{
				"label": "夏集镇",
				"value": "8167",
				"childrens": []
			}, {
				"label": "尚塘乡",
				"value": "8168",
				"childrens": []
			}, {
				"label": "朱马店镇",
				"value": "8169",
				"childrens": []
			}, {
				"label": "顾桥镇",
				"value": "8170",
				"childrens": []
			}, {
				"label": "经济开发区",
				"value": "8171",
				"childrens": []
			}, {
				"label": "岳张集镇",
				"value": "8172",
				"childrens": []
			}, {
				"label": "新集镇",
				"value": "8173",
				"childrens": []
			}, {
				"label": "丁集乡",
				"value": "8174",
				"childrens": []
			}, {
				"label": "桂集镇",
				"value": "8175",
				"childrens": []
			}, {
				"label": "钱庙乡",
				"value": "8176",
				"childrens": []
			}, {
				"label": "大兴集乡",
				"value": "8177",
				"childrens": []
			}, {
				"label": "李冲回族乡",
				"value": "8178",
				"childrens": []
			}, {
				"label": "杨村乡",
				"value": "8179",
				"childrens": []
			}, {
				"label": "凤凰镇",
				"value": "8180",
				"childrens": []
			}, {
				"label": "毛集镇",
				"value": "8181",
				"childrens": []
			}, {
				"label": "古店乡",
				"value": "8182",
				"childrens": []
			}, {
				"label": "焦岗湖镇",
				"value": "8183",
				"childrens": []
			}, {
				"label": "刘集乡",
				"value": "8184",
				"childrens": []
			}, {
				"label": "城关镇",
				"value": "8185",
				"childrens": []
			}, {
				"label": "关店乡",
				"value": "8186",
				"childrens": []
			}]
		}, {
			"label": "田家庵区",
			"value": "3447",
			"childrens": [{
				"label": "淮滨街道",
				"value": "8239",
				"childrens": []
			}, {
				"label": "史院乡",
				"value": "8240",
				"childrens": []
			}, {
				"label": "洞山街道",
				"value": "8241",
				"childrens": []
			}, {
				"label": "泉山街道",
				"value": "8242",
				"childrens": []
			}, {
				"label": "曹庵镇",
				"value": "8243",
				"childrens": []
			}, {
				"label": "公园街道",
				"value": "8244",
				"childrens": []
			}, {
				"label": "新淮街道",
				"value": "8245",
				"childrens": []
			}, {
				"label": "龙泉街道",
				"value": "8246",
				"childrens": []
			}, {
				"label": "国庆街道",
				"value": "8247",
				"childrens": []
			}, {
				"label": "田东街道",
				"value": "8248",
				"childrens": []
			}, {
				"label": "安成镇",
				"value": "8249",
				"childrens": []
			}, {
				"label": "朝阳街道",
				"value": "8250",
				"childrens": []
			}, {
				"label": "舜耕镇",
				"value": "8251",
				"childrens": []
			}, {
				"label": "三和乡",
				"value": "8252",
				"childrens": []
			}]
		}, {
			"label": "大通区",
			"value": "3448",
			"childrens": [{
				"label": "大通街道",
				"value": "8233",
				"childrens": []
			}, {
				"label": "上窑镇",
				"value": "8234",
				"childrens": []
			}, {
				"label": "孔店乡",
				"value": "8235",
				"childrens": []
			}, {
				"label": "洛河镇",
				"value": "8236",
				"childrens": []
			}, {
				"label": "九龙岗镇",
				"value": "8237",
				"childrens": []
			}, {
				"label": "淮南经济开发区",
				"value": "8238",
				"childrens": []
			}]
		}, {
			"label": "谢家集区",
			"value": "3449",
			"childrens": [{
				"label": "唐山镇",
				"value": "8253",
				"childrens": []
			}, {
				"label": "李郢孜镇",
				"value": "8254",
				"childrens": []
			}, {
				"label": "平山街道",
				"value": "8255",
				"childrens": []
			}, {
				"label": "孤堆乡",
				"value": "8256",
				"childrens": []
			}, {
				"label": "谢家集街道",
				"value": "8257",
				"childrens": []
			}, {
				"label": "望峰岗镇",
				"value": "8258",
				"childrens": []
			}, {
				"label": "谢三村街道",
				"value": "8259",
				"childrens": []
			}, {
				"label": "蔡家岗街道",
				"value": "8260",
				"childrens": []
			}, {
				"label": "孙庙乡",
				"value": "8261",
				"childrens": []
			}, {
				"label": "立新街道",
				"value": "8262",
				"childrens": []
			}, {
				"label": "杨公镇",
				"value": "8263",
				"childrens": []
			}]
		}, {
			"label": "八公山区",
			"value": "3450",
			"childrens": [{
				"label": "毕家岗街道",
				"value": "8227",
				"childrens": []
			}, {
				"label": "妙山林场",
				"value": "8228",
				"childrens": []
			}, {
				"label": "土坝孜街道",
				"value": "8229",
				"childrens": []
			}, {
				"label": "八公山镇",
				"value": "8230",
				"childrens": []
			}, {
				"label": "新庄孜街道",
				"value": "8231",
				"childrens": []
			}, {
				"label": "山王镇",
				"value": "8232",
				"childrens": []
			}]
		}, {
			"label": "潘集区",
			"value": "3451",
			"childrens": [{
				"label": "架河镇",
				"value": "8156",
				"childrens": []
			}, {
				"label": "平圩镇",
				"value": "8157",
				"childrens": []
			}, {
				"label": "潘集镇",
				"value": "8158",
				"childrens": []
			}, {
				"label": "田集街道",
				"value": "8159",
				"childrens": []
			}, {
				"label": "贺疃乡",
				"value": "8160",
				"childrens": []
			}, {
				"label": "祁集乡",
				"value": "8161",
				"childrens": []
			}, {
				"label": "芦集镇",
				"value": "8162",
				"childrens": []
			}, {
				"label": "古沟回族乡",
				"value": "8163",
				"childrens": []
			}, {
				"label": "泥河镇",
				"value": "8164",
				"childrens": []
			}, {
				"label": "高皇镇",
				"value": "8165",
				"childrens": []
			}, {
				"label": "夹沟乡",
				"value": "8166",
				"childrens": []
			}]
		}, {
			"label": "淮南高新技术开发区",
			"value": "4960",
			"childrens": []
		}, {
			"label": "寿县",
			"value": "53487",
			"childrens": []
		}]
	}, {
		"label": "淮北市",
		"value": "1124",
		"childrens": [{
			"label": "杜集区",
			"value": "53488",
			"childrens": []
		}, {
			"label": "烈山区",
			"value": "53489",
			"childrens": []
		}, {
			"label": "濉溪县",
			"value": "53490",
			"childrens": []
		}, {
			"label": "相山区",
			"value": "53491",
			"childrens": []
		}]
	}, {
		"label": "芜湖市",
		"value": "1127",
		"childrens": [{
			"label": "芜湖县",
			"value": "1128",
			"childrens": []
		}, {
			"label": "繁昌县",
			"value": "1129",
			"childrens": []
		}, {
			"label": "南陵县",
			"value": "1130",
			"childrens": []
		}, {
			"label": "无为县",
			"value": "1189",
			"childrens": []
		}, {
			"label": "镜湖区",
			"value": "3438",
			"childrens": []
		}, {
			"label": "弋江区",
			"value": "4172",
			"childrens": []
		}, {
			"label": "鸠江区",
			"value": "53492",
			"childrens": []
		}, {
			"label": "三山区",
			"value": "53493",
			"childrens": []
		}]
	}, {
		"label": "蚌埠市",
		"value": "1132",
		"childrens": [{
			"label": "怀远县",
			"value": "1133",
			"childrens": []
		}, {
			"label": "固镇县",
			"value": "1134",
			"childrens": []
		}, {
			"label": "五河县",
			"value": "1135",
			"childrens": []
		}, {
			"label": "蚌山区",
			"value": "3442",
			"childrens": []
		}, {
			"label": "淮上区",
			"value": "53494",
			"childrens": []
		}, {
			"label": "龙子湖区",
			"value": "53495",
			"childrens": []
		}, {
			"label": "禹会区",
			"value": "53496",
			"childrens": []
		}]
	}, {
		"label": "马鞍山市",
		"value": "1137",
		"childrens": [{
			"label": "当涂县",
			"value": "1138",
			"childrens": []
		}, {
			"label": "含山县",
			"value": "1187",
			"childrens": []
		}, {
			"label": "和县",
			"value": "1188",
			"childrens": []
		}, {
			"label": "博望区",
			"value": "6963",
			"childrens": []
		}, {
			"label": "花山区",
			"value": "53497",
			"childrens": []
		}, {
			"label": "雨山区",
			"value": "53498",
			"childrens": []
		}]
	}, {
		"label": "安庆市",
		"value": "1140",
		"childrens": [{
			"label": "桐城市",
			"value": "1141",
			"childrens": []
		}, {
			"label": "宿松县",
			"value": "1142",
			"childrens": []
		}, {
			"label": "枞阳县",
			"value": "1143",
			"childrens": []
		}, {
			"label": "太湖县",
			"value": "1144",
			"childrens": []
		}, {
			"label": "怀宁县",
			"value": "1145",
			"childrens": []
		}, {
			"label": "岳西县",
			"value": "1146",
			"childrens": []
		}, {
			"label": "望江县",
			"value": "1147",
			"childrens": []
		}, {
			"label": "潜山县",
			"value": "1148",
			"childrens": []
		}, {
			"label": "大观区",
			"value": "4075",
			"childrens": []
		}, {
			"label": "宜秀区",
			"value": "53499",
			"childrens": []
		}, {
			"label": "迎江区",
			"value": "53500",
			"childrens": []
		}]
	}, {
		"label": "黄山市",
		"value": "1151",
		"childrens": [{
			"label": "休宁县",
			"value": "1153",
			"childrens": []
		}, {
			"label": "歙县",
			"value": "1154",
			"childrens": []
		}, {
			"label": "黟县",
			"value": "1155",
			"childrens": []
		}, {
			"label": "祁门县",
			"value": "1156",
			"childrens": []
		}, {
			"label": "黄山区",
			"value": "3464",
			"childrens": []
		}, {
			"label": "徽州区",
			"value": "53501",
			"childrens": []
		}, {
			"label": "屯溪区",
			"value": "53502",
			"childrens": []
		}]
	}, {
		"label": "滁州市",
		"value": "1159",
		"childrens": [{
			"label": "明光市",
			"value": "1161",
			"childrens": []
		}, {
			"label": "全椒县",
			"value": "1162",
			"childrens": []
		}, {
			"label": "来安县",
			"value": "1163",
			"childrens": []
		}, {
			"label": "定远县",
			"value": "1164",
			"childrens": []
		}, {
			"label": "凤阳县",
			"value": "1165",
			"childrens": []
		}, {
			"label": "南谯区",
			"value": "3467",
			"childrens": []
		}, {
			"label": "琅琊区",
			"value": "53503",
			"childrens": []
		}, {
			"label": "天长市",
			"value": "53504",
			"childrens": []
		}]
	}, {
		"label": "阜阳市",
		"value": "1167",
		"childrens": [{
			"label": "界首市",
			"value": "1168",
			"childrens": []
		}, {
			"label": "太和县",
			"value": "1169",
			"childrens": []
		}, {
			"label": "阜南县",
			"value": "1170",
			"childrens": []
		}, {
			"label": "颍上县",
			"value": "1171",
			"childrens": []
		}, {
			"label": "临泉县",
			"value": "1172",
			"childrens": []
		}, {
			"label": "经济开发区",
			"value": "4832",
			"childrens": []
		}, {
			"label": "颍泉区",
			"value": "53505",
			"childrens": []
		}, {
			"label": "颍州区",
			"value": "53506",
			"childrens": []
		}, {
			"label": "颍东区",
			"value": "53507",
			"childrens": []
		}]
	}, {
		"label": "亳州市",
		"value": "1174",
		"childrens": [{
			"label": "利辛县",
			"value": "1176",
			"childrens": []
		}, {
			"label": "蒙城县",
			"value": "1177",
			"childrens": []
		}, {
			"label": "涡阳县",
			"value": "1178",
			"childrens": []
		}, {
			"label": "谯城区",
			"value": "53508",
			"childrens": []
		}]
	}, {
		"label": "宿州市",
		"value": "1180",
		"childrens": [{
			"label": "灵璧县",
			"value": "1181",
			"childrens": []
		}, {
			"label": "泗县",
			"value": "1182",
			"childrens": []
		}, {
			"label": "萧县",
			"value": "1183",
			"childrens": []
		}, {
			"label": "砀山县",
			"value": "1184",
			"childrens": []
		}, {
			"label": "经济开发区",
			"value": "6006",
			"childrens": []
		}, {
			"label": "埇桥区",
			"value": "53509",
			"childrens": []
		}]
	}, {
		"label": "池州市",
		"value": "1201",
		"childrens": [{
			"label": "东至县",
			"value": "1202",
			"childrens": []
		}, {
			"label": "石台县",
			"value": "1203",
			"childrens": []
		}, {
			"label": "青阳县",
			"value": "1204",
			"childrens": []
		}, {
			"label": "贵池区",
			"value": "53510",
			"childrens": []
		}]
	}, {
		"label": "六安市",
		"value": "1206",
		"childrens": [{
			"label": "寿县",
			"value": "1207",
			"childrens": []
		}, {
			"label": "霍山县",
			"value": "1208",
			"childrens": []
		}, {
			"label": "金寨县",
			"value": "1209",
			"childrens": []
		}, {
			"label": "霍邱县",
			"value": "1210",
			"childrens": []
		}, {
			"label": "舒城县",
			"value": "1211",
			"childrens": []
		}, {
			"label": "金安区",
			"value": "53511",
			"childrens": []
		}, {
			"label": "裕安区",
			"value": "53512",
			"childrens": []
		}, {
			"label": "叶集区",
			"value": "53513",
			"childrens": []
		}]
	}, {
		"label": "宣城市",
		"value": "2971",
		"childrens": [{
			"label": "泾县",
			"value": "2972",
			"childrens": []
		}, {
			"label": "旌德县",
			"value": "3128",
			"childrens": []
		}, {
			"label": "宁国市",
			"value": "3147",
			"childrens": []
		}, {
			"label": "郎溪县",
			"value": "3477",
			"childrens": []
		}, {
			"label": "广德县",
			"value": "3478",
			"childrens": []
		}, {
			"label": "绩溪县",
			"value": "3479",
			"childrens": []
		}, {
			"label": "宣州区",
			"value": "53514",
			"childrens": []
		}]
	}]
}, {
	"label": "广东",
	"value": "19",
	"childrens": [{
		"label": "广州市",
		"value": "1601",
		"childrens": [{
			"label": "天河区",
			"value": "3633",
			"childrens": []
		}, {
			"label": "海珠区",
			"value": "3634",
			"childrens": []
		}, {
			"label": "荔湾区",
			"value": "3635",
			"childrens": []
		}, {
			"label": "越秀区",
			"value": "3637",
			"childrens": []
		}, {
			"label": "番禺区",
			"value": "53039",
			"childrens": []
		}, {
			"label": "花都区",
			"value": "53040",
			"childrens": []
		}, {
			"label": "白云区",
			"value": "53041",
			"childrens": []
		}, {
			"label": "南沙区",
			"value": "53042",
			"childrens": []
		}, {
			"label": "黄埔区",
			"value": "53043",
			"childrens": []
		}, {
			"label": "增城区",
			"value": "53044",
			"childrens": []
		}, {
			"label": "从化区",
			"value": "53045",
			"childrens": []
		}, {
			"label": "广州大学城",
			"value": "53046",
			"childrens": []
		}]
	}, {
		"label": "深圳市",
		"value": "1607",
		"childrens": [{
			"label": "南山区",
			"value": "3155",
			"childrens": []
		}, {
			"label": "罗湖区",
			"value": "3638",
			"childrens": []
		}, {
			"label": "福田区",
			"value": "3639",
			"childrens": []
		}, {
			"label": "宝安区",
			"value": "4773",
			"childrens": []
		}, {
			"label": "光明新区",
			"value": "6675",
			"childrens": []
		}, {
			"label": "坪山新区",
			"value": "6736",
			"childrens": []
		}, {
			"label": "大鹏新区",
			"value": "6737",
			"childrens": []
		}, {
			"label": "龙岗区",
			"value": "53047",
			"childrens": []
		}, {
			"label": "盐田区",
			"value": "53048",
			"childrens": []
		}, {
			"label": "龙华区",
			"value": "53049",
			"childrens": []
		}]
	}, {
		"label": "珠海市",
		"value": "1609",
		"childrens": [{
			"label": "斗门区",
			"value": "53050",
			"childrens": []
		}, {
			"label": "金湾区",
			"value": "53051",
			"childrens": []
		}, {
			"label": "香洲区",
			"value": "53052",
			"childrens": []
		}]
	}, {
		"label": "汕头市",
		"value": "1611",
		"childrens": [{
			"label": "南澳县",
			"value": "1614",
			"childrens": []
		}, {
			"label": "龙湖区",
			"value": "53053",
			"childrens": []
		}, {
			"label": "金平区",
			"value": "53054",
			"childrens": []
		}, {
			"label": "澄海区",
			"value": "53055",
			"childrens": []
		}, {
			"label": "潮阳区",
			"value": "53056",
			"childrens": []
		}, {
			"label": "潮南区",
			"value": "53057",
			"childrens": []
		}, {
			"label": "濠江区",
			"value": "53058",
			"childrens": []
		}]
	}, {
		"label": "韶关市",
		"value": "1617",
		"childrens": [{
			"label": "南雄市",
			"value": "1618",
			"childrens": [{
				"label": "百顺镇",
				"value": "6275",
				"childrens": []
			}, {
				"label": "邓坊镇",
				"value": "6276",
				"childrens": []
			}, {
				"label": "湖口镇",
				"value": "6277",
				"childrens": []
			}, {
				"label": "黄坑镇",
				"value": "6278",
				"childrens": []
			}, {
				"label": "江头镇",
				"value": "6279",
				"childrens": []
			}, {
				"label": "界址镇",
				"value": "6280",
				"childrens": []
			}, {
				"label": "澜河镇",
				"value": "6281",
				"childrens": []
			}, {
				"label": "帽子峰镇",
				"value": "6282",
				"childrens": []
			}, {
				"label": "南亩镇",
				"value": "6283",
				"childrens": []
			}, {
				"label": "水口镇",
				"value": "6284",
				"childrens": []
			}, {
				"label": "坪田镇",
				"value": "6285",
				"childrens": []
			}, {
				"label": "全安镇",
				"value": "6286",
				"childrens": []
			}, {
				"label": "乌迳镇",
				"value": "6287",
				"childrens": []
			}, {
				"label": "油山镇",
				"value": "6289",
				"childrens": []
			}, {
				"label": "珠玑镇",
				"value": "6290",
				"childrens": []
			}, {
				"label": "主田镇",
				"value": "6291",
				"childrens": []
			}, {
				"label": "古市镇",
				"value": "6292",
				"childrens": []
			}, {
				"label": "精细化工基地",
				"value": "9162",
				"childrens": []
			}]
		}, {
			"label": "乐昌市",
			"value": "1619",
			"childrens": [{
				"label": "白石镇",
				"value": "6293",
				"childrens": []
			}, {
				"label": "北乡镇",
				"value": "6294",
				"childrens": []
			}, {
				"label": "大源镇",
				"value": "6295",
				"childrens": []
			}, {
				"label": "黄圃镇",
				"value": "6296",
				"childrens": []
			}, {
				"label": "九峰镇",
				"value": "6297",
				"childrens": []
			}, {
				"label": "廊田镇",
				"value": "6298",
				"childrens": []
			}, {
				"label": "两江镇",
				"value": "6300",
				"childrens": []
			}, {
				"label": "梅花镇",
				"value": "6301",
				"childrens": []
			}, {
				"label": "坪石镇",
				"value": "6302",
				"childrens": []
			}, {
				"label": "庆云镇",
				"value": "6303",
				"childrens": []
			}, {
				"label": "三溪镇",
				"value": "6304",
				"childrens": []
			}, {
				"label": "沙坪镇",
				"value": "6305",
				"childrens": []
			}, {
				"label": "五山镇",
				"value": "6306",
				"childrens": []
			}, {
				"label": "秀水镇",
				"value": "6307",
				"childrens": []
			}, {
				"label": "云岩镇",
				"value": "6308",
				"childrens": []
			}, {
				"label": "长来镇",
				"value": "6309",
				"childrens": []
			}, {
				"label": "河南镇",
				"value": "9160",
				"childrens": []
			}, {
				"label": "乐城镇",
				"value": "9161",
				"childrens": []
			}]
		}, {
			"label": "仁化县",
			"value": "1620",
			"childrens": [{
				"label": "城口镇",
				"value": "6310",
				"childrens": []
			}, {
				"label": "大桥镇",
				"value": "6311",
				"childrens": []
			}, {
				"label": "董塘镇",
				"value": "6313",
				"childrens": []
			}, {
				"label": "扶溪镇",
				"value": "6314",
				"childrens": []
			}, {
				"label": "红山镇",
				"value": "6315",
				"childrens": []
			}, {
				"label": "黄坑镇",
				"value": "6316",
				"childrens": []
			}, {
				"label": "石塘镇",
				"value": "6317",
				"childrens": []
			}, {
				"label": "闻韶镇",
				"value": "6318",
				"childrens": []
			}, {
				"label": "长江镇",
				"value": "6319",
				"childrens": []
			}, {
				"label": "周田镇",
				"value": "6320",
				"childrens": []
			}]
		}, {
			"label": "始兴县",
			"value": "1621",
			"childrens": [{
				"label": "隘子镇",
				"value": "6321",
				"childrens": []
			}, {
				"label": "城南镇",
				"value": "6322",
				"childrens": []
			}, {
				"label": "澄江镇",
				"value": "6323",
				"childrens": []
			}, {
				"label": "顿岗镇",
				"value": "6324",
				"childrens": []
			}, {
				"label": "罗坝镇",
				"value": "6325",
				"childrens": []
			}, {
				"label": "马市镇",
				"value": "6326",
				"childrens": []
			}, {
				"label": "深渡水瑶族乡",
				"value": "6327",
				"childrens": []
			}, {
				"label": "沈所镇",
				"value": "6328",
				"childrens": []
			}, {
				"label": "司前镇",
				"value": "6329",
				"childrens": []
			}, {
				"label": "太平镇",
				"value": "6330",
				"childrens": []
			}]
		}, {
			"label": "翁源县",
			"value": "1622",
			"childrens": [{
				"label": "坝仔镇",
				"value": "6331",
				"childrens": []
			}, {
				"label": "官渡镇",
				"value": "6332",
				"childrens": []
			}, {
				"label": "江尾镇",
				"value": "6333",
				"childrens": []
			}, {
				"label": "龙仙镇",
				"value": "6334",
				"childrens": []
			}, {
				"label": "翁城镇",
				"value": "6335",
				"childrens": []
			}, {
				"label": "新江镇",
				"value": "6336",
				"childrens": []
			}, {
				"label": "周陂镇",
				"value": "6337",
				"childrens": []
			}, {
				"label": "铁龙林场",
				"value": "9155",
				"childrens": []
			}]
		}, {
			"label": "新丰县",
			"value": "1624",
			"childrens": [{
				"label": "黄礤镇",
				"value": "6348",
				"childrens": []
			}, {
				"label": "回龙镇",
				"value": "6349",
				"childrens": []
			}, {
				"label": "马头镇",
				"value": "6350",
				"childrens": []
			}, {
				"label": "梅坑镇",
				"value": "6351",
				"childrens": []
			}, {
				"label": "沙田镇",
				"value": "6352",
				"childrens": []
			}, {
				"label": "遥田镇",
				"value": "6353",
				"childrens": []
			}]
		}, {
			"label": "乳源瑶族自治县",
			"value": "1625",
			"childrens": [{
				"label": "必背镇",
				"value": "6354",
				"childrens": []
			}, {
				"label": "大布镇",
				"value": "6355",
				"childrens": []
			}, {
				"label": "大桥镇",
				"value": "6356",
				"childrens": []
			}, {
				"label": "东坪镇",
				"value": "6357",
				"childrens": []
			}, {
				"label": "桂头镇",
				"value": "6358",
				"childrens": []
			}, {
				"label": "洛阳镇",
				"value": "6359",
				"childrens": []
			}, {
				"label": "乳城镇",
				"value": "6360",
				"childrens": []
			}, {
				"label": "一六镇",
				"value": "6361",
				"childrens": []
			}, {
				"label": "游溪镇",
				"value": "6362",
				"childrens": []
			}, {
				"label": "天井山林场",
				"value": "9156",
				"childrens": []
			}, {
				"label": "乳阳林业局",
				"value": "9157",
				"childrens": []
			}]
		}, {
			"label": "曲江区",
			"value": "1626",
			"childrens": [{
				"label": "马坝镇",
				"value": "8193",
				"childrens": []
			}, {
				"label": "樟市镇",
				"value": "8194",
				"childrens": []
			}, {
				"label": "韶关冶炼厂",
				"value": "8195",
				"childrens": []
			}, {
				"label": "沙溪镇",
				"value": "8196",
				"childrens": []
			}, {
				"label": "韶关钢铁集团有限公司",
				"value": "8197",
				"childrens": []
			}, {
				"label": "小坑镇",
				"value": "8198",
				"childrens": []
			}, {
				"label": "乌石镇",
				"value": "8199",
				"childrens": []
			}, {
				"label": "枫湾镇",
				"value": "8200",
				"childrens": []
			}, {
				"label": "罗坑镇",
				"value": "8201",
				"childrens": []
			}, {
				"label": "韶关十六冶金建设公司",
				"value": "8202",
				"childrens": []
			}, {
				"label": "白土镇",
				"value": "8203",
				"childrens": []
			}, {
				"label": "大塘镇",
				"value": "8204",
				"childrens": []
			}, {
				"label": "韶关发电厂",
				"value": "8205",
				"childrens": []
			}, {
				"label": "曲江区大宝山矿",
				"value": "8206",
				"childrens": []
			}]
		}, {
			"label": "武江区",
			"value": "3643",
			"childrens": [{
				"label": "重阳镇",
				"value": "8207",
				"childrens": []
			}, {
				"label": "西河片区",
				"value": "8208",
				"childrens": []
			}, {
				"label": "江湾镇",
				"value": "8209",
				"childrens": []
			}, {
				"label": "龙归镇",
				"value": "8210",
				"childrens": []
			}, {
				"label": "沙洲尾",
				"value": "8211",
				"childrens": []
			}, {
				"label": "西联镇",
				"value": "8212",
				"childrens": []
			}, {
				"label": "沐溪工业园",
				"value": "8213",
				"childrens": []
			}]
		}, {
			"label": "浈江区",
			"value": "3644",
			"childrens": [{
				"label": "东联片区",
				"value": "8214",
				"childrens": []
			}, {
				"label": "东河片区",
				"value": "8216",
				"childrens": []
			}, {
				"label": "韶关大学",
				"value": "8217",
				"childrens": []
			}, {
				"label": "犁市镇",
				"value": "8219",
				"childrens": []
			}, {
				"label": "花坪镇",
				"value": "8221",
				"childrens": []
			}, {
				"label": "乐园镇",
				"value": "8222",
				"childrens": []
			}, {
				"label": "五里亭",
				"value": "8223",
				"childrens": []
			}, {
				"label": "十里亭镇",
				"value": "8225",
				"childrens": []
			}, {
				"label": "南郊片区",
				"value": "8226",
				"childrens": []
			}]
		}]
	}, {
		"label": "河源市",
		"value": "1627",
		"childrens": [{
			"label": "和平县",
			"value": "1628",
			"childrens": [{
				"label": "阳明镇",
				"value": "6010",
				"childrens": []
			}, {
				"label": "彭寨镇",
				"value": "6011",
				"childrens": []
			}, {
				"label": "东水镇",
				"value": "6012",
				"childrens": []
			}, {
				"label": "林寨镇",
				"value": "6013",
				"childrens": []
			}, {
				"label": "热水镇",
				"value": "6014",
				"childrens": []
			}, {
				"label": "大坝镇",
				"value": "6015",
				"childrens": []
			}, {
				"label": "上陵镇",
				"value": "6016",
				"childrens": []
			}, {
				"label": "下车镇",
				"value": "6017",
				"childrens": []
			}, {
				"label": "贝墩镇",
				"value": "6018",
				"childrens": []
			}, {
				"label": "古寨镇",
				"value": "6019",
				"childrens": []
			}, {
				"label": "礼士镇",
				"value": "6020",
				"childrens": []
			}, {
				"label": "公白镇",
				"value": "6021",
				"childrens": []
			}, {
				"label": "合水镇",
				"value": "6022",
				"childrens": []
			}, {
				"label": "青州镇",
				"value": "6023",
				"childrens": []
			}, {
				"label": "浰源镇",
				"value": "6024",
				"childrens": []
			}, {
				"label": "优胜镇",
				"value": "6025",
				"childrens": []
			}]
		}, {
			"label": "龙川县",
			"value": "1629",
			"childrens": [{
				"label": "老隆镇",
				"value": "6026",
				"childrens": []
			}, {
				"label": "四都镇",
				"value": "6027",
				"childrens": []
			}, {
				"label": "黄石镇",
				"value": "6028",
				"childrens": []
			}, {
				"label": "细坳镇",
				"value": "6029",
				"childrens": []
			}, {
				"label": "车田镇",
				"value": "6030",
				"childrens": []
			}, {
				"label": "贝岭镇",
				"value": "6031",
				"childrens": []
			}, {
				"label": "黎咀镇",
				"value": "6032",
				"childrens": []
			}, {
				"label": "上坪镇",
				"value": "6033",
				"childrens": []
			}, {
				"label": "丰稔镇",
				"value": "6034",
				"childrens": []
			}, {
				"label": "赤光镇",
				"value": "6035",
				"childrens": []
			}, {
				"label": "龙母镇",
				"value": "6036",
				"childrens": []
			}, {
				"label": "回龙镇",
				"value": "6037",
				"childrens": []
			}, {
				"label": "铁场镇",
				"value": "6038",
				"childrens": []
			}, {
				"label": "登云镇",
				"value": "6039",
				"childrens": []
			}, {
				"label": "通衢镇",
				"value": "6040",
				"childrens": []
			}, {
				"label": "鹤市镇",
				"value": "6041",
				"childrens": []
			}, {
				"label": "黄布镇",
				"value": "6043",
				"childrens": []
			}, {
				"label": "紫市镇",
				"value": "6044",
				"childrens": []
			}, {
				"label": "佗城镇",
				"value": "6045",
				"childrens": []
			}, {
				"label": "岩镇",
				"value": "6046",
				"childrens": []
			}, {
				"label": "新田镇",
				"value": "6047",
				"childrens": []
			}, {
				"label": "附城镇",
				"value": "6048",
				"childrens": []
			}, {
				"label": "义都镇",
				"value": "6049",
				"childrens": []
			}, {
				"label": "麻布岗镇",
				"value": "6050",
				"childrens": []
			}]
		}, {
			"label": "紫金县",
			"value": "1630",
			"childrens": [{
				"label": "紫城镇",
				"value": "6051",
				"childrens": []
			}, {
				"label": "附城镇",
				"value": "6052",
				"childrens": []
			}, {
				"label": "九和镇",
				"value": "6053",
				"childrens": []
			}, {
				"label": "上义镇",
				"value": "6054",
				"childrens": []
			}, {
				"label": "蓝塘镇",
				"value": "6055",
				"childrens": []
			}, {
				"label": "凤安镇",
				"value": "6056",
				"childrens": []
			}, {
				"label": "义容镇",
				"value": "6057",
				"childrens": []
			}, {
				"label": "古竹镇",
				"value": "6058",
				"childrens": []
			}, {
				"label": "临江镇",
				"value": "6059",
				"childrens": []
			}, {
				"label": "柏埔镇",
				"value": "6060",
				"childrens": []
			}, {
				"label": "敬梓镇",
				"value": "6061",
				"childrens": []
			}, {
				"label": "乌石镇",
				"value": "6062",
				"childrens": []
			}, {
				"label": "水墩镇",
				"value": "6063",
				"childrens": []
			}, {
				"label": "南岭镇",
				"value": "6064",
				"childrens": []
			}, {
				"label": "苏区镇",
				"value": "6065",
				"childrens": []
			}, {
				"label": "瓦溪镇",
				"value": "6066",
				"childrens": []
			}, {
				"label": "好义镇",
				"value": "6067",
				"childrens": []
			}, {
				"label": "中坝镇",
				"value": "6068",
				"childrens": []
			}, {
				"label": "龙窝镇",
				"value": "6069",
				"childrens": []
			}]
		}, {
			"label": "连平县",
			"value": "1631",
			"childrens": [{
				"label": "元善镇",
				"value": "6071",
				"childrens": []
			}, {
				"label": "上坪镇",
				"value": "6072",
				"childrens": []
			}, {
				"label": "内莞镇",
				"value": "6073",
				"childrens": []
			}, {
				"label": "陂头镇",
				"value": "6074",
				"childrens": []
			}, {
				"label": "溪山镇",
				"value": "6075",
				"childrens": []
			}, {
				"label": "隆街镇",
				"value": "6076",
				"childrens": []
			}, {
				"label": "田源镇",
				"value": "6077",
				"childrens": []
			}, {
				"label": "油溪镇",
				"value": "6078",
				"childrens": []
			}, {
				"label": "忠信镇",
				"value": "6079",
				"childrens": []
			}, {
				"label": "高莞镇",
				"value": "6080",
				"childrens": []
			}, {
				"label": "大湖镇",
				"value": "6081",
				"childrens": []
			}, {
				"label": "三角镇",
				"value": "6082",
				"childrens": []
			}, {
				"label": "绣缎镇",
				"value": "6083",
				"childrens": []
			}]
		}, {
			"label": "源城区",
			"value": "53059",
			"childrens": []
		}, {
			"label": "东源县",
			"value": "53060",
			"childrens": []
		}]
	}, {
		"label": "梅州市",
		"value": "1634",
		"childrens": [{
			"label": "兴宁市",
			"value": "1635",
			"childrens": [{
				"label": "罗浮镇",
				"value": "8519",
				"childrens": []
			}, {
				"label": "罗岗镇",
				"value": "8520",
				"childrens": []
			}, {
				"label": "坭陂镇",
				"value": "8521",
				"childrens": []
			}, {
				"label": "石马镇",
				"value": "8522",
				"childrens": []
			}, {
				"label": "合水镇",
				"value": "8523",
				"childrens": []
			}, {
				"label": "新陂镇",
				"value": "8524",
				"childrens": []
			}, {
				"label": "永和镇",
				"value": "8525",
				"childrens": []
			}, {
				"label": "刁坊镇",
				"value": "8526",
				"childrens": []
			}, {
				"label": "径南镇",
				"value": "8527",
				"childrens": []
			}, {
				"label": "水口镇",
				"value": "8528",
				"childrens": []
			}, {
				"label": "黄陂镇",
				"value": "8529",
				"childrens": []
			}, {
				"label": "黄槐镇",
				"value": "8531",
				"childrens": []
			}, {
				"label": "宁中镇",
				"value": "8532",
				"childrens": []
			}, {
				"label": "龙田镇",
				"value": "8533",
				"childrens": []
			}, {
				"label": "叶塘镇",
				"value": "8534",
				"childrens": []
			}, {
				"label": "新圩镇",
				"value": "8535",
				"childrens": []
			}, {
				"label": "大坪镇",
				"value": "8536",
				"childrens": []
			}]
		}, {
			"label": "梅县",
			"value": "1636",
			"childrens": [{
				"label": "畲江镇",
				"value": "8420",
				"childrens": []
			}, {
				"label": "雁洋镇",
				"value": "8421",
				"childrens": []
			}, {
				"label": "石扇镇",
				"value": "8422",
				"childrens": []
			}, {
				"label": "白渡镇",
				"value": "8423",
				"childrens": []
			}, {
				"label": "梅西镇",
				"value": "8424",
				"childrens": []
			}, {
				"label": "南口镇",
				"value": "8425",
				"childrens": []
			}, {
				"label": "城东镇",
				"value": "8426",
				"childrens": []
			}, {
				"label": "梅县新城",
				"value": "8427",
				"childrens": []
			}, {
				"label": "梅南镇",
				"value": "8428",
				"childrens": []
			}, {
				"label": "程江镇",
				"value": "8429",
				"childrens": []
			}, {
				"label": "西阳镇",
				"value": "8430",
				"childrens": []
			}, {
				"label": "水车镇",
				"value": "8431",
				"childrens": []
			}, {
				"label": "松源镇",
				"value": "8432",
				"childrens": []
			}, {
				"label": "松口镇",
				"value": "8433",
				"childrens": []
			}, {
				"label": "梅西水库",
				"value": "8434",
				"childrens": []
			}, {
				"label": "桃尧镇",
				"value": "8435",
				"childrens": []
			}, {
				"label": "丙村镇",
				"value": "8436",
				"childrens": []
			}, {
				"label": "隆文镇",
				"value": "8437",
				"childrens": []
			}, {
				"label": "扶大镇",
				"value": "8438",
				"childrens": []
			}, {
				"label": "大坪镇",
				"value": "8439",
				"childrens": []
			}, {
				"label": "石坑镇",
				"value": "8440",
				"childrens": []
			}]
		}, {
			"label": "蕉岭县",
			"value": "1637",
			"childrens": [{
				"label": "文福镇",
				"value": "8509",
				"childrens": []
			}, {
				"label": "新铺镇",
				"value": "8510",
				"childrens": []
			}, {
				"label": "三圳镇",
				"value": "8511",
				"childrens": []
			}, {
				"label": "蓝坊镇",
				"value": "8512",
				"childrens": []
			}, {
				"label": "南礤镇",
				"value": "8513",
				"childrens": []
			}, {
				"label": "广福镇",
				"value": "8514",
				"childrens": []
			}, {
				"label": "华侨农场",
				"value": "8515",
				"childrens": []
			}, {
				"label": "蕉城镇",
				"value": "8516",
				"childrens": []
			}, {
				"label": "长潭镇",
				"value": "8517",
				"childrens": []
			}]
		}, {
			"label": "大埔县",
			"value": "1638",
			"childrens": [{
				"label": "青溪镇",
				"value": "8447",
				"childrens": []
			}, {
				"label": "银江镇",
				"value": "8448",
				"childrens": []
			}, {
				"label": "湖寮镇",
				"value": "8449",
				"childrens": []
			}, {
				"label": "三河镇",
				"value": "8450",
				"childrens": []
			}, {
				"label": "大麻镇",
				"value": "8451",
				"childrens": []
			}, {
				"label": "洲瑞镇",
				"value": "8452",
				"childrens": []
			}, {
				"label": "桃源镇",
				"value": "8453",
				"childrens": []
			}, {
				"label": "丰溪林场",
				"value": "8454",
				"childrens": []
			}, {
				"label": "光德镇",
				"value": "8455",
				"childrens": []
			}, {
				"label": "枫朗镇",
				"value": "8456",
				"childrens": []
			}, {
				"label": "洲瑞林场",
				"value": "8457",
				"childrens": []
			}, {
				"label": "高陂镇",
				"value": "8458",
				"childrens": []
			}, {
				"label": "大埔林场",
				"value": "8459",
				"childrens": []
			}, {
				"label": "大东镇",
				"value": "8460",
				"childrens": []
			}, {
				"label": "茶阳镇",
				"value": "8461",
				"childrens": []
			}, {
				"label": "百侯镇",
				"value": "8462",
				"childrens": []
			}, {
				"label": "西河镇",
				"value": "8463",
				"childrens": []
			}]
		}, {
			"label": "丰顺县",
			"value": "1639",
			"childrens": [{
				"label": "汤南镇",
				"value": "8464",
				"childrens": []
			}, {
				"label": "汤西镇",
				"value": "8465",
				"childrens": []
			}, {
				"label": "砂田镇",
				"value": "8466",
				"childrens": []
			}, {
				"label": "大龙华镇",
				"value": "8467",
				"childrens": []
			}, {
				"label": "埔寨镇",
				"value": "8468",
				"childrens": []
			}, {
				"label": "八乡山镇",
				"value": "8469",
				"childrens": []
			}, {
				"label": "潘田镇",
				"value": "8470",
				"childrens": []
			}, {
				"label": "龙岗镇",
				"value": "8471",
				"childrens": []
			}, {
				"label": "黄金镇",
				"value": "8472",
				"childrens": []
			}, {
				"label": "建桥镇",
				"value": "8473",
				"childrens": []
			}, {
				"label": "汤坑镇",
				"value": "8474",
				"childrens": []
			}, {
				"label": "留隍镇",
				"value": "8475",
				"childrens": []
			}, {
				"label": "北斗镇",
				"value": "8476",
				"childrens": []
			}, {
				"label": "埔寨农场",
				"value": "8477",
				"childrens": []
			}, {
				"label": "丰良镇",
				"value": "8478",
				"childrens": []
			}, {
				"label": "潭江镇",
				"value": "8479",
				"childrens": []
			}, {
				"label": "小胜镇",
				"value": "8480",
				"childrens": []
			}]
		}, {
			"label": "五华县",
			"value": "1640",
			"childrens": [{
				"label": "棉洋镇",
				"value": "8481",
				"childrens": []
			}, {
				"label": "郭田镇",
				"value": "8482",
				"childrens": []
			}, {
				"label": "潭下镇",
				"value": "8483",
				"childrens": []
			}, {
				"label": "周江镇",
				"value": "8484",
				"childrens": []
			}, {
				"label": "岐岭镇",
				"value": "8485",
				"childrens": []
			}, {
				"label": "横陂镇",
				"value": "8486",
				"childrens": []
			}, {
				"label": "华城镇",
				"value": "8487",
				"childrens": []
			}, {
				"label": "安流镇",
				"value": "8488",
				"childrens": []
			}, {
				"label": "转水镇",
				"value": "8489",
				"childrens": []
			}, {
				"label": "华阳镇",
				"value": "8490",
				"childrens": []
			}, {
				"label": "长布镇",
				"value": "8491",
				"childrens": []
			}, {
				"label": "水寨镇",
				"value": "8492",
				"childrens": []
			}, {
				"label": "河东镇",
				"value": "8493",
				"childrens": []
			}, {
				"label": "梅林镇",
				"value": "8494",
				"childrens": []
			}, {
				"label": "龙村镇",
				"value": "8495",
				"childrens": []
			}, {
				"label": "双华镇",
				"value": "8496",
				"childrens": []
			}]
		}, {
			"label": "平远县",
			"value": "1641",
			"childrens": [{
				"label": "热柘镇",
				"value": "8497",
				"childrens": []
			}, {
				"label": "长田镇",
				"value": "8498",
				"childrens": []
			}, {
				"label": "大柘镇",
				"value": "8499",
				"childrens": []
			}, {
				"label": "仁居镇",
				"value": "8500",
				"childrens": []
			}, {
				"label": "泗水镇",
				"value": "8501",
				"childrens": []
			}, {
				"label": "河头镇",
				"value": "8502",
				"childrens": []
			}, {
				"label": "上举镇",
				"value": "8503",
				"childrens": []
			}, {
				"label": "差干镇",
				"value": "8504",
				"childrens": []
			}, {
				"label": "八尺镇",
				"value": "8505",
				"childrens": []
			}, {
				"label": "石正镇",
				"value": "8506",
				"childrens": []
			}, {
				"label": "东石镇",
				"value": "8507",
				"childrens": []
			}, {
				"label": "中行镇",
				"value": "8508",
				"childrens": []
			}]
		}, {
			"label": "梅江区",
			"value": "1642",
			"childrens": [{
				"label": "江北片区",
				"value": "8441",
				"childrens": []
			}, {
				"label": "三角镇",
				"value": "8442",
				"childrens": []
			}, {
				"label": "城北镇",
				"value": "8444",
				"childrens": []
			}, {
				"label": "江南市区",
				"value": "8445",
				"childrens": []
			}, {
				"label": "长沙镇",
				"value": "8446",
				"childrens": []
			}]
		}]
	}, {
		"label": "惠州市",
		"value": "1643",
		"childrens": [{
			"label": "龙门县",
			"value": "1647",
			"childrens": []
		}, {
			"label": "惠阳区",
			"value": "53061",
			"childrens": []
		}, {
			"label": "大亚湾区",
			"value": "53062",
			"childrens": []
		}, {
			"label": "惠城区",
			"value": "53063",
			"childrens": []
		}, {
			"label": "惠东县",
			"value": "53064",
			"childrens": []
		}, {
			"label": "博罗县",
			"value": "53065",
			"childrens": []
		}]
	}, {
		"label": "汕尾市",
		"value": "1650",
		"childrens": [{
			"label": "陆河县",
			"value": "1653",
			"childrens": [{
				"label": "河田镇",
				"value": "6145",
				"childrens": []
			}, {
				"label": "新田镇",
				"value": "6146",
				"childrens": []
			}, {
				"label": "南万镇",
				"value": "6147",
				"childrens": []
			}, {
				"label": "螺溪镇",
				"value": "6148",
				"childrens": []
			}, {
				"label": "河口镇",
				"value": "6149",
				"childrens": []
			}, {
				"label": "东坑镇",
				"value": "6150",
				"childrens": []
			}, {
				"label": "水唇镇",
				"value": "6151",
				"childrens": []
			}, {
				"label": "上护镇",
				"value": "6152",
				"childrens": []
			}]
		}, {
			"label": "海丰县",
			"value": "3037",
			"childrens": [{
				"label": "海城镇",
				"value": "6153",
				"childrens": []
			}, {
				"label": "梅陇镇",
				"value": "6154",
				"childrens": []
			}, {
				"label": "附城镇",
				"value": "6155",
				"childrens": []
			}, {
				"label": "联安镇",
				"value": "6156",
				"childrens": []
			}, {
				"label": "陶河镇",
				"value": "6157",
				"childrens": []
			}, {
				"label": "可塘镇",
				"value": "6158",
				"childrens": []
			}, {
				"label": "赤坑镇",
				"value": "6159",
				"childrens": []
			}, {
				"label": "公平镇",
				"value": "6160",
				"childrens": []
			}, {
				"label": "城东镇",
				"value": "6161",
				"childrens": []
			}, {
				"label": "黄羌镇",
				"value": "6162",
				"childrens": []
			}, {
				"label": "平东镇",
				"value": "6163",
				"childrens": []
			}, {
				"label": "鹅埠镇",
				"value": "6164",
				"childrens": []
			}, {
				"label": "赤石镇",
				"value": "6165",
				"childrens": []
			}, {
				"label": "鮜门镇",
				"value": "6166",
				"childrens": []
			}, {
				"label": "小漠镇",
				"value": "6167",
				"childrens": []
			}, {
				"label": "大湖镇",
				"value": "6168",
				"childrens": []
			}]
		}, {
			"label": "城区",
			"value": "53067",
			"childrens": []
		}, {
			"label": "陆丰市",
			"value": "53068",
			"childrens": []
		}]
	}, {
		"label": "东莞市",
		"value": "1655",
		"childrens": [{
			"label": "中堂镇",
			"value": "2950",
			"childrens": []
		}, {
			"label": "东坑镇",
			"value": "3041",
			"childrens": []
		}, {
			"label": "道滘镇",
			"value": "3078",
			"childrens": []
		}, {
			"label": "沙田镇",
			"value": "3097",
			"childrens": []
		}, {
			"label": "高埗镇",
			"value": "3100",
			"childrens": []
		}, {
			"label": "石龙镇",
			"value": "3102",
			"childrens": []
		}, {
			"label": "石排镇",
			"value": "3104",
			"childrens": []
		}, {
			"label": "企石镇",
			"value": "3105",
			"childrens": []
		}, {
			"label": "石碣镇",
			"value": "3111",
			"childrens": []
		}, {
			"label": "洪梅镇",
			"value": "3116",
			"childrens": []
		}, {
			"label": "麻涌镇",
			"value": "3120",
			"childrens": []
		}, {
			"label": "桥头镇",
			"value": "3134",
			"childrens": []
		}, {
			"label": "望牛墩镇",
			"value": "3151",
			"childrens": []
		}, {
			"label": "茶山镇",
			"value": "3171",
			"childrens": []
		}, {
			"label": "谢岗镇",
			"value": "4087",
			"childrens": []
		}, {
			"label": "松山湖",
			"value": "4147",
			"childrens": []
		}, {
			"label": "莞城区",
			"value": "4255",
			"childrens": []
		}, {
			"label": "南城区",
			"value": "4256",
			"childrens": []
		}, {
			"label": "长安镇",
			"value": "4760",
			"childrens": []
		}, {
			"label": "寮步镇",
			"value": "4866",
			"childrens": []
		}, {
			"label": "大岭山镇",
			"value": "4871",
			"childrens": []
		}, {
			"label": "常平镇",
			"value": "4886",
			"childrens": []
		}, {
			"label": "厚街镇",
			"value": "4910",
			"childrens": []
		}, {
			"label": "万江区",
			"value": "4911",
			"childrens": []
		}, {
			"label": "樟木头镇",
			"value": "4932",
			"childrens": []
		}, {
			"label": "大朗镇",
			"value": "4980",
			"childrens": []
		}, {
			"label": "塘厦镇",
			"value": "5457",
			"childrens": []
		}, {
			"label": "凤岗镇",
			"value": "5473",
			"childrens": []
		}, {
			"label": "清溪镇",
			"value": "5869",
			"childrens": []
		}, {
			"label": "横沥镇",
			"value": "5905",
			"childrens": []
		}, {
			"label": "东城区",
			"value": "53069",
			"childrens": []
		}, {
			"label": "黄江镇",
			"value": "53070",
			"childrens": []
		}, {
			"label": "虎门镇",
			"value": "53071",
			"childrens": []
		}]
	}, {
		"label": "中山市",
		"value": "1657",
		"childrens": [{
			"label": "南朗镇",
			"value": "2777",
			"childrens": []
		}, {
			"label": "小榄镇",
			"value": "2902",
			"childrens": []
		}, {
			"label": "古镇",
			"value": "2957",
			"childrens": []
		}, {
			"label": "坦洲镇",
			"value": "3001",
			"childrens": []
		}, {
			"label": "黄圃镇",
			"value": "3007",
			"childrens": []
		}, {
			"label": "三乡镇",
			"value": "3016",
			"childrens": []
		}, {
			"label": "东凤镇",
			"value": "3067",
			"childrens": []
		}, {
			"label": "横栏镇",
			"value": "3112",
			"childrens": []
		}, {
			"label": "三角镇",
			"value": "3143",
			"childrens": []
		}, {
			"label": "南头镇",
			"value": "3176",
			"childrens": []
		}, {
			"label": "沙溪镇",
			"value": "3743",
			"childrens": []
		}, {
			"label": "五桂山镇",
			"value": "4042",
			"childrens": []
		}, {
			"label": "阜沙镇",
			"value": "4076",
			"childrens": []
		}, {
			"label": "东升镇",
			"value": "4080",
			"childrens": []
		}, {
			"label": "板芙镇",
			"value": "4102",
			"childrens": []
		}, {
			"label": "神湾镇",
			"value": "4127",
			"childrens": []
		}, {
			"label": "港口镇",
			"value": "4141",
			"childrens": []
		}, {
			"label": "大涌镇",
			"value": "4190",
			"childrens": []
		}, {
			"label": "火炬开发区",
			"value": "4852",
			"childrens": []
		}, {
			"label": "民众镇",
			"value": "8540",
			"childrens": []
		}, {
			"label": "沙朗镇",
			"value": "53072",
			"childrens": []
		}, {
			"label": "城区",
			"value": "53073",
			"childrens": []
		}]
	}, {
		"label": "江门市",
		"value": "1659",
		"childrens": [{
			"label": "台山市",
			"value": "53074",
			"childrens": []
		}, {
			"label": "新会区",
			"value": "53075",
			"childrens": []
		}, {
			"label": "鹤山市",
			"value": "53076",
			"childrens": []
		}, {
			"label": "江海区",
			"value": "53077",
			"childrens": []
		}, {
			"label": "蓬江区",
			"value": "53078",
			"childrens": []
		}, {
			"label": "开平市",
			"value": "53079",
			"childrens": []
		}, {
			"label": "恩平市",
			"value": "53080",
			"childrens": []
		}]
	}, {
		"label": "佛山市",
		"value": "1666",
		"childrens": [{
			"label": "顺德区",
			"value": "1669",
			"childrens": []
		}, {
			"label": "禅城区",
			"value": "53081",
			"childrens": []
		}, {
			"label": "高明区",
			"value": "53082",
			"childrens": []
		}, {
			"label": "三水区",
			"value": "53083",
			"childrens": []
		}, {
			"label": "南海区",
			"value": "53084",
			"childrens": []
		}]
	}, {
		"label": "阳江市",
		"value": "1672",
		"childrens": [{
			"label": "阳春市",
			"value": "1673",
			"childrens": [{
				"label": "八甲镇",
				"value": "6475",
				"childrens": []
			}, {
				"label": "陂面镇",
				"value": "6476",
				"childrens": []
			}, {
				"label": "合水镇",
				"value": "6477",
				"childrens": []
			}, {
				"label": "春湾镇",
				"value": "6479",
				"childrens": []
			}, {
				"label": "岗美镇",
				"value": "6480",
				"childrens": []
			}, {
				"label": "圭岗镇",
				"value": "6481",
				"childrens": []
			}, {
				"label": "石望镇",
				"value": "6482",
				"childrens": []
			}, {
				"label": "河口镇",
				"value": "6483",
				"childrens": []
			}, {
				"label": "河塱镇",
				"value": "6484",
				"childrens": []
			}, {
				"label": "松柏镇",
				"value": "6485",
				"childrens": []
			}, {
				"label": "马水镇",
				"value": "6486",
				"childrens": []
			}, {
				"label": "三甲镇",
				"value": "6487",
				"childrens": []
			}, {
				"label": "双窖镇",
				"value": "6488",
				"childrens": []
			}, {
				"label": "潭水镇",
				"value": "6489",
				"childrens": []
			}, {
				"label": "永宁镇",
				"value": "6490",
				"childrens": []
			}]
		}, {
			"label": "阳西县",
			"value": "1674",
			"childrens": [{
				"label": "织篢镇",
				"value": "6493",
				"childrens": []
			}, {
				"label": "程村镇",
				"value": "6494",
				"childrens": []
			}, {
				"label": "溪头镇",
				"value": "6495",
				"childrens": []
			}, {
				"label": "上洋镇",
				"value": "6496",
				"childrens": []
			}, {
				"label": "沙扒镇",
				"value": "6497",
				"childrens": []
			}, {
				"label": "儒洞镇",
				"value": "6498",
				"childrens": []
			}, {
				"label": "新圩镇",
				"value": "6499",
				"childrens": []
			}, {
				"label": "塘口镇",
				"value": "6500",
				"childrens": []
			}]
		}, {
			"label": "江城区",
			"value": "53085",
			"childrens": []
		}, {
			"label": "阳东县",
			"value": "53086",
			"childrens": []
		}]
	}, {
		"label": "湛江市",
		"value": "1677",
		"childrens": [{
			"label": "雷州市",
			"value": "1679",
			"childrens": [{
				"label": "白沙镇",
				"value": "6385",
				"childrens": []
			}, {
				"label": "北和镇",
				"value": "6386",
				"childrens": []
			}, {
				"label": "东里镇",
				"value": "6387",
				"childrens": []
			}, {
				"label": "附城镇",
				"value": "6388",
				"childrens": []
			}, {
				"label": "纪家镇",
				"value": "6389",
				"childrens": []
			}, {
				"label": "雷高镇",
				"value": "6391",
				"childrens": []
			}, {
				"label": "龙门镇",
				"value": "6392",
				"childrens": []
			}, {
				"label": "南兴镇",
				"value": "6393",
				"childrens": []
			}, {
				"label": "企水镇",
				"value": "6394",
				"childrens": []
			}, {
				"label": "沈塘镇",
				"value": "6395",
				"childrens": []
			}, {
				"label": "松竹镇",
				"value": "6396",
				"childrens": []
			}, {
				"label": "覃斗镇",
				"value": "6397",
				"childrens": []
			}, {
				"label": "唐家镇",
				"value": "6398",
				"childrens": []
			}, {
				"label": "调风镇",
				"value": "6399",
				"childrens": []
			}, {
				"label": "乌石镇",
				"value": "6400",
				"childrens": []
			}, {
				"label": "客路镇",
				"value": "6402",
				"childrens": []
			}, {
				"label": "杨家镇",
				"value": "6404",
				"childrens": []
			}, {
				"label": "英利镇",
				"value": "6405",
				"childrens": []
			}]
		}, {
			"label": "吴川市",
			"value": "1680",
			"childrens": [{
				"label": "黄坡镇",
				"value": "6410",
				"childrens": []
			}, {
				"label": "兰石镇",
				"value": "6411",
				"childrens": []
			}, {
				"label": "覃巴镇",
				"value": "6413",
				"childrens": []
			}, {
				"label": "塘缀镇",
				"value": "6415",
				"childrens": []
			}, {
				"label": "王村港",
				"value": "6416",
				"childrens": []
			}, {
				"label": "吴阳镇",
				"value": "6417",
				"childrens": []
			}, {
				"label": "樟铺镇",
				"value": "6418",
				"childrens": []
			}, {
				"label": "长岐镇",
				"value": "6419",
				"childrens": []
			}, {
				"label": "振文镇",
				"value": "6420",
				"childrens": []
			}, {
				"label": "浅水镇",
				"value": "6422",
				"childrens": []
			}]
		}, {
			"label": "徐闻县",
			"value": "1682",
			"childrens": [{
				"label": "和安镇",
				"value": "6424",
				"childrens": []
			}, {
				"label": "曲界镇",
				"value": "6425",
				"childrens": []
			}, {
				"label": "锦和镇",
				"value": "6426",
				"childrens": []
			}, {
				"label": "新寮镇",
				"value": "6427",
				"childrens": []
			}, {
				"label": "下洋镇",
				"value": "6428",
				"childrens": []
			}, {
				"label": "前山镇",
				"value": "6429",
				"childrens": []
			}, {
				"label": "龙塘镇",
				"value": "6430",
				"childrens": []
			}, {
				"label": "海安镇",
				"value": "6431",
				"childrens": []
			}, {
				"label": "迈陈镇",
				"value": "6432",
				"childrens": []
			}, {
				"label": "西连镇",
				"value": "6433",
				"childrens": []
			}, {
				"label": "下桥镇",
				"value": "6434",
				"childrens": []
			}, {
				"label": "南山镇",
				"value": "6435",
				"childrens": []
			}, {
				"label": "城北乡",
				"value": "6436",
				"childrens": []
			}, {
				"label": "角尾乡",
				"value": "6437",
				"childrens": []
			}]
		}, {
			"label": "坡头区",
			"value": "3646",
			"childrens": [{
				"label": "坡头镇",
				"value": "6447",
				"childrens": []
			}, {
				"label": "龙头镇",
				"value": "6448",
				"childrens": []
			}, {
				"label": "乾塘镇",
				"value": "6449",
				"childrens": []
			}, {
				"label": "南三镇",
				"value": "6450",
				"childrens": []
			}, {
				"label": "官渡镇",
				"value": "6451",
				"childrens": []
			}]
		}, {
			"label": "赤坎区",
			"value": "53087",
			"childrens": []
		}, {
			"label": "霞山区",
			"value": "53088",
			"childrens": []
		}, {
			"label": "经济技术开发区",
			"value": "53089",
			"childrens": []
		}, {
			"label": "麻章区",
			"value": "53090",
			"childrens": []
		}, {
			"label": "遂溪县",
			"value": "53091",
			"childrens": []
		}, {
			"label": "廉江市",
			"value": "53092",
			"childrens": []
		}]
	}, {
		"label": "茂名市",
		"value": "1684",
		"childrens": [{
			"label": "信宜市",
			"value": "1687",
			"childrens": [{
				"label": "白石镇",
				"value": "6219",
				"childrens": []
			}, {
				"label": "北界镇",
				"value": "6220",
				"childrens": []
			}, {
				"label": "茶山镇",
				"value": "6221",
				"childrens": []
			}, {
				"label": "池洞镇",
				"value": "6222",
				"childrens": []
			}, {
				"label": "大成镇",
				"value": "6223",
				"childrens": []
			}, {
				"label": "丁堡镇",
				"value": "6224",
				"childrens": []
			}, {
				"label": "贵子镇",
				"value": "6226",
				"childrens": []
			}, {
				"label": "合水镇",
				"value": "6227",
				"childrens": []
			}, {
				"label": "洪冠镇",
				"value": "6228",
				"childrens": []
			}, {
				"label": "怀乡镇",
				"value": "6229",
				"childrens": []
			}, {
				"label": "金垌镇",
				"value": "6230",
				"childrens": []
			}, {
				"label": "平塘镇",
				"value": "6231",
				"childrens": []
			}, {
				"label": "钱排镇",
				"value": "6232",
				"childrens": []
			}, {
				"label": "水口镇",
				"value": "6233",
				"childrens": []
			}, {
				"label": "思贺镇",
				"value": "6234",
				"childrens": []
			}, {
				"label": "新宝镇",
				"value": "6235",
				"childrens": []
			}, {
				"label": "镇隆镇",
				"value": "6236",
				"childrens": []
			}, {
				"label": "朱砂镇",
				"value": "6237",
				"childrens": []
			}]
		}, {
			"label": "茂南区",
			"value": "53093",
			"childrens": []
		}, {
			"label": "电白区",
			"value": "53094",
			"childrens": []
		}, {
			"label": "高州市",
			"value": "53095",
			"childrens": []
		}, {
			"label": "化州市",
			"value": "53096",
			"childrens": []
		}]
	}, {
		"label": "肇庆市",
		"value": "1690",
		"childrens": [{
			"label": "广宁县",
			"value": "1693",
			"childrens": []
		}, {
			"label": "德庆县",
			"value": "1694",
			"childrens": []
		}, {
			"label": "怀集县",
			"value": "1695",
			"childrens": []
		}, {
			"label": "封开县",
			"value": "1696",
			"childrens": []
		}, {
			"label": "鼎湖区",
			"value": "1697",
			"childrens": []
		}, {
			"label": "端州区",
			"value": "4781",
			"childrens": []
		}, {
			"label": "四会市",
			"value": "53097",
			"childrens": []
		}, {
			"label": "高要市",
			"value": "53098",
			"childrens": []
		}]
	}, {
		"label": "云浮市",
		"value": "1698",
		"childrens": [{
			"label": "云安县",
			"value": "1700",
			"childrens": [{
				"label": "六都镇",
				"value": "6525",
				"childrens": []
			}, {
				"label": "前锋镇",
				"value": "6526",
				"childrens": []
			}, {
				"label": "南盛镇",
				"value": "6527",
				"childrens": []
			}, {
				"label": "富林镇",
				"value": "6528",
				"childrens": []
			}, {
				"label": "镇安镇",
				"value": "6529",
				"childrens": []
			}, {
				"label": "白石镇",
				"value": "6530",
				"childrens": []
			}, {
				"label": "高村镇",
				"value": "6531",
				"childrens": []
			}, {
				"label": "石城镇",
				"value": "6532",
				"childrens": []
			}]
		}, {
			"label": "新兴县",
			"value": "1701",
			"childrens": [{
				"label": "新城镇",
				"value": "6533",
				"childrens": []
			}, {
				"label": "水台镇",
				"value": "6534",
				"childrens": []
			}, {
				"label": "车岗镇",
				"value": "6535",
				"childrens": []
			}, {
				"label": "东成镇",
				"value": "6536",
				"childrens": []
			}, {
				"label": "稔村镇",
				"value": "6537",
				"childrens": []
			}, {
				"label": "太平镇",
				"value": "6538",
				"childrens": []
			}, {
				"label": "六祖镇",
				"value": "6539",
				"childrens": []
			}, {
				"label": "大江镇",
				"value": "6540",
				"childrens": []
			}, {
				"label": "河头镇",
				"value": "6541",
				"childrens": []
			}, {
				"label": "天堂镇",
				"value": "6542",
				"childrens": []
			}, {
				"label": "簕竹镇",
				"value": "6543",
				"childrens": []
			}, {
				"label": "里洞镇",
				"value": "6544",
				"childrens": []
			}]
		}, {
			"label": "郁南县",
			"value": "1702",
			"childrens": [{
				"label": "都城镇",
				"value": "6545",
				"childrens": []
			}, {
				"label": "东坝镇",
				"value": "6546",
				"childrens": []
			}, {
				"label": "宋桂镇",
				"value": "6547",
				"childrens": []
			}, {
				"label": "连滩镇",
				"value": "6548",
				"childrens": []
			}, {
				"label": "大湾镇",
				"value": "6549",
				"childrens": []
			}, {
				"label": "建城镇",
				"value": "6551",
				"childrens": []
			}, {
				"label": "千官镇",
				"value": "6552",
				"childrens": []
			}, {
				"label": "通门镇",
				"value": "6553",
				"childrens": []
			}, {
				"label": "桂圩镇",
				"value": "6554",
				"childrens": []
			}, {
				"label": "宝珠镇",
				"value": "6555",
				"childrens": []
			}, {
				"label": "历洞镇",
				"value": "6556",
				"childrens": []
			}, {
				"label": "大方镇",
				"value": "6557",
				"childrens": []
			}, {
				"label": "南江口镇",
				"value": "6558",
				"childrens": []
			}, {
				"label": "平台镇",
				"value": "6559",
				"childrens": []
			}]
		}, {
			"label": "云城区",
			"value": "53100",
			"childrens": []
		}, {
			"label": "罗定市",
			"value": "53101",
			"childrens": []
		}]
	}, {
		"label": "清远市",
		"value": "1704",
		"childrens": [{
			"label": "连州市",
			"value": "1795",
			"childrens": []
		}, {
			"label": "佛冈县",
			"value": "1796",
			"childrens": []
		}, {
			"label": "阳山县",
			"value": "1797",
			"childrens": []
		}, {
			"label": "清新县",
			"value": "1798",
			"childrens": []
		}, {
			"label": "连山县",
			"value": "1799",
			"childrens": []
		}, {
			"label": "连南县",
			"value": "1800",
			"childrens": []
		}, {
			"label": "清城区",
			"value": "53102",
			"childrens": []
		}, {
			"label": "英德市",
			"value": "53103",
			"childrens": []
		}]
	}, {
		"label": "潮州市",
		"value": "1705",
		"childrens": [{
			"label": "饶平县",
			"value": "1707",
			"childrens": []
		}, {
			"label": "枫溪区",
			"value": "4238",
			"childrens": []
		}, {
			"label": "湘桥区",
			"value": "53104",
			"childrens": []
		}, {
			"label": "潮安区",
			"value": "53105",
			"childrens": []
		}]
	}, {
		"label": "揭阳市",
		"value": "1709",
		"childrens": [{
			"label": "揭西县",
			"value": "1712",
			"childrens": [{
				"label": "龙潭镇",
				"value": "6086",
				"childrens": []
			}, {
				"label": "南山镇",
				"value": "6087",
				"childrens": []
			}, {
				"label": "五经富镇",
				"value": "6088",
				"childrens": []
			}, {
				"label": "京溪园镇",
				"value": "6089",
				"childrens": []
			}, {
				"label": "灰寨镇",
				"value": "6090",
				"childrens": []
			}, {
				"label": "塔头镇",
				"value": "6091",
				"childrens": []
			}, {
				"label": "东园镇",
				"value": "6092",
				"childrens": []
			}, {
				"label": "棉湖镇",
				"value": "6093",
				"childrens": []
			}, {
				"label": "金和镇",
				"value": "6094",
				"childrens": []
			}, {
				"label": "大溪镇",
				"value": "6095",
				"childrens": []
			}, {
				"label": "钱坑镇",
				"value": "6096",
				"childrens": []
			}, {
				"label": "坪上镇",
				"value": "6097",
				"childrens": []
			}, {
				"label": "五云镇",
				"value": "6098",
				"childrens": []
			}, {
				"label": "上砂镇",
				"value": "6099",
				"childrens": []
			}, {
				"label": "良田乡",
				"value": "6100",
				"childrens": []
			}]
		}, {
			"label": "惠来县",
			"value": "1713",
			"childrens": [{
				"label": "惠城镇",
				"value": "6101",
				"childrens": []
			}, {
				"label": "华湖镇",
				"value": "6102",
				"childrens": []
			}, {
				"label": "仙庵镇",
				"value": "6103",
				"childrens": []
			}, {
				"label": "靖海镇",
				"value": "6104",
				"childrens": []
			}, {
				"label": "周田镇",
				"value": "6105",
				"childrens": []
			}, {
				"label": "前詹镇",
				"value": "6106",
				"childrens": []
			}, {
				"label": "神泉镇",
				"value": "6107",
				"childrens": []
			}, {
				"label": "东陇镇",
				"value": "6108",
				"childrens": []
			}, {
				"label": "岐石镇",
				"value": "6109",
				"childrens": []
			}, {
				"label": "隆江镇",
				"value": "6110",
				"childrens": []
			}, {
				"label": "溪西镇",
				"value": "6111",
				"childrens": []
			}, {
				"label": "鳌江镇",
				"value": "6112",
				"childrens": []
			}, {
				"label": "东港镇",
				"value": "6113",
				"childrens": []
			}, {
				"label": "葵潭镇",
				"value": "6114",
				"childrens": []
			}]
		}, {
			"label": "东山区",
			"value": "5484",
			"childrens": []
		}, {
			"label": "普宁市",
			"value": "5864",
			"childrens": []
		}, {
			"label": "榕城区",
			"value": "53106",
			"childrens": []
		}, {
			"label": "揭东县",
			"value": "53107",
			"childrens": []
		}]
	}]
}, {
	"label": "宁夏",
	"value": "30",
	"childrens": [{
		"label": "银川市",
		"value": "2628",
		"childrens": [{
			"label": "灵武市",
			"value": "2629",
			"childrens": []
		}, {
			"label": "永宁县",
			"value": "2630",
			"childrens": []
		}, {
			"label": "贺兰县",
			"value": "2631",
			"childrens": []
		}, {
			"label": "兴庆区",
			"value": "53764",
			"childrens": []
		}, {
			"label": "金凤区",
			"value": "53765",
			"childrens": []
		}, {
			"label": "西夏区",
			"value": "53766",
			"childrens": []
		}]
	}, {
		"label": "石嘴山市",
		"value": "2632",
		"childrens": [{
			"label": "平罗县",
			"value": "2633",
			"childrens": []
		}, {
			"label": "惠农区",
			"value": "2635",
			"childrens": []
		}, {
			"label": "大武口区",
			"value": "2636",
			"childrens": []
		}]
	}, {
		"label": "吴忠市",
		"value": "2637",
		"childrens": [{
			"label": "青铜峡市",
			"value": "2638",
			"childrens": []
		}, {
			"label": "同心县",
			"value": "2641",
			"childrens": []
		}, {
			"label": "盐池县",
			"value": "2642",
			"childrens": []
		}, {
			"label": "红寺堡开发区",
			"value": "2643",
			"childrens": []
		}, {
			"label": "利通区",
			"value": "2966",
			"childrens": []
		}]
	}, {
		"label": "固原市",
		"value": "2644",
		"childrens": [{
			"label": "西吉县",
			"value": "2647",
			"childrens": []
		}, {
			"label": "隆德县",
			"value": "2648",
			"childrens": []
		}, {
			"label": "泾源县",
			"value": "2649",
			"childrens": []
		}, {
			"label": "彭阳县",
			"value": "2650",
			"childrens": []
		}, {
			"label": "原州区",
			"value": "2651",
			"childrens": []
		}]
	}, {
		"label": "中卫市",
		"value": "3071",
		"childrens": [{
			"label": "中宁县",
			"value": "3072",
			"childrens": []
		}, {
			"label": "海原县",
			"value": "3148",
			"childrens": []
		}, {
			"label": "沙坡头区",
			"value": "4020",
			"childrens": []
		}]
	}]
}]



export default {

	jd
}
 